apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.webapp.deploymentName }}
spec:
  replicas: {{ .values.deploymentReplicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx
      labels:
        app: web
    spec:
      containers:
      - name: {{ .values.webapp.containerName }}
        image: {{ .values.webapp.dockerImage }}
        ports:
        - containerPort: {{ values.services.port }}
