apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  ports:
  - targetPort: {{ values.services.port }}
    port: {{ values.services.port }}
    nodePort: {{ .values.services.nodePort }}
  selector:
    apps: web
